name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: ryuichiueda/ubuntu22.04-ros2:latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up ROS 2 workspace
      run: |
        mkdir -p ~/ros2_ws/src
        rsync -av ./ ~/ros2_ws/src/hw2/homework2
    - name: Build and Test
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/ros2_ws
        colcon build --packages-select homework2
        source install/setup.bash
        bash -xv src/hw2/homework2/homework2/test/test.bash ~

