name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Prepare workspace
        run: |
          mkdir -p /root/ros2_ws/src/hw2/homework2
      - name: Sync source code
        run: |
          rsync -av ./ /root/ros2_ws/src/hw2/homework2/
      - name: Build and Test
        run: |
          # bashシェルを明示的に使用
          bash -c "cd /root/ros2_ws && source /opt/ros/humble/setup.bash && colcon build --symlink-install --packages-select homework2 && source install/setup.bash && bash -xv ./src/hw2/homework2/test/test.bash /root"
