name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    env:
      ROS_DISTRO: humble  # ROS2のディストリビューション名を指定
    steps:
      - uses: actions/checkout@v2
      - name: Setup ROS2 APT repository
        run: |
          apt-get update && apt-get install -y curl gnupg2 lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
          echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list
          apt-get update
      - name: Install Python3 and dependencies
        run: |
          apt-get install -y python3 python3-pip python3-colcon-common-extensions
          ln -sf /usr/bin/python3 /usr/bin/python
      - name: Set COLCON_PYTHON_EXECUTABLE
        run: echo "export COLCON_PYTHON_EXECUTABLE=/usr/bin/python3" >> $GITHUB_ENV
      - name: Install ROS2 Python bindings
        run: |
          apt-get install -y ros-${ROS_DISTRO}-rclpy ros-${ROS_DISTRO}-std-msgs
      - name: Build and test
        shell: bash  # ここで bash を指定
        run: |
          rsync -av ./ /root/ros2_ws/src/homework2/
          cd /root/ros2_ws
          colcon build
          source install/setup.bash
          bash -xv ./src/homework2/test/test.bash /root

